# Generated by Django 2.2.7 on 2020-03-30 19:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 30, 19, 1, 25, 407063, tzinfo=utc))),
                ('add', models.BooleanField(default=True, verbose_name='Добавлять')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing.Thing')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
